var decimal = 6;
var hex = 0xf00d;
var binary = 9;
var octal = 511;
document.write(binary.toString());
var color = "blue";
color = 'red';
var fullName = "Bob Bobbington";
var age = 37;
var sentence = "Hello, my name is " + fullName + ".\n\nI'll be " + (age + 1) + " years old next month.";
document.write(sentence);
